# -*- coding: utf-8 -*-
"""2_day_61_descession_tree_visualizaion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LU9nfoJ_7131RxhkcwGVhPMsjczsro7q
"""

pip install dtreeviz

import graphviz.backend as be

from sklearn.datasets import *
from IPython.display import Image,display_svg,SVG

from sklearn.tree import DecisionTreeClassifier
clas=DecisionTreeClassifier(max_depth=2)
iris=load_iris()

x_train=iris.data
y_train=iris.target
clas.fit(x_train,y_train)

from sklearn.tree import plot_tree
plot_tree(clas)

"""**1.Classification**"""

import dtreeviz

m = dtreeviz.model(
    clas,
    X_train=X_train,
    y_train=y_train,
    feature_names=iris.feature_names,
    # target_name="species",
    class_names=list(iris.target_names)
)

viz = m.view(scale=1.5)
viz

m = dtreeviz.model(
    clas,
    X_train=X_train,
    y_train=y_train,
    feature_names=iris.feature_names,
    # target_name="species",
    # orientation="LR",
    class_names=list(iris.target_names)

)

viz = m.view(scale=1.5)
viz

